version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: fake build

deploy:
  - provider: NuGet
    api_key:
      secure: Uy3IZ06Fk5KLIlt9Jsbeafm2RpSBs3rPf+jGxgm2qHCGO8d8wwiEJpnc2nXPeBTn
    on:
      appveyor_repo_tag: true
