version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

cache:
  - '%LOCALAPPDATA%\\Yarn -> yarn.lock'
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: fake build

deploy:
  - provider: NuGet
    api_key:
      secure: 2Ux7tZOWHVhvcQg1/H3PbBVQPDDsWFzEx/BZOls7D3MD74BySErPKxi9i8aQ3KHu
    on:
      appveyor_repo_tag: true
